version: "3.8"

services:
  selenium-hub:
    image: selenium/hub:latest  # Use the latest stable version
    container_name: selenium-hub
    ports:
      - "4444:4444"  # Exposes the Selenium Grid UI
    environment:
      - GRID_MAX_SESSION=10
      - GRID_SESSION_TIMEOUT=300
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome:4.12.0
    container_name: node-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm  # Improves browser performance
    networks:
      - selenium-grid

  firefox:
    image: selenium/node-firefox:4.12.0
    container_name: node-firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm  # Improves browser performance
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge